version: '3.4'

networks:
    blockchainapp:

services:
    blockchain.api:
        image: ${DOCKER_REGISTRY-}blockchainapi
        build:
            context: .
            dockerfile: Blockchain.API\Dockerfile
        ports:
            - "5000:5000"
            - "5001:5001" 
        depends_on:
            - blockchaindb

    blockchaindb:
        image:  mcr.microsoft.com/mssql/server:2022-latest 
        container_name: blockchaindb
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=123456a@
            - MSSQL_PID=Express
        volumes:
          - C:\dados\volumes\sqlserver:/var/opt/mssql/data
        ports:
            - 1433:1433

    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672