version: '3.4'

networks:
    blockchain:

services:
    blockchain.api:
        platform: linux/amd64
        image: ${DOCKER_REGISTRY-}blockchainapi
        build:
            context: .
            dockerfile: Blockchain.API\Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081" 
        depends_on:
            - blockchaindb
        environment:
            - FIREBASE_PROJECT_ID=blockchain-b2f62
            - FIREBASE_JSON_CREDENTIALS={"type":"service_account","project_id":"blockchain-b2f62","private_key_id":"bab887fca226f5e6fb99a21a9e384b5e19e1976f","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYNOnEgz0T0GVx\nr7FKywDcZY1MPSTYyXkbOm0RVDuBj7eWDrJL07XEL7sluz4ChlW74JtB38h4zmjk\n1g/OeHYfPBAg8dyHSn2vGJhh47m9GUs2qmkv5venR10XdFHYQQW1u7ZS+ZPMeAwe\nKOcyEmcI9BELbjg4DYroykKXr4nq9ztOor9Lv74QuiM3eOCCfujRYcmCvUibYcNP\nxbnuw4Tjo3IZnZf/kEvXj05CyIykarThSmnNfZl39I/Psz2ZnkosVCL1CuuMI+ak\ns00ndoehNOcL3feH1yweDgo2TbgFB67xeyzeddRsQYk3Fc9WwpYMLok1q5soR6hh\nUGvd+oXjAgMBAAECggEAGqOyZgcxoF5eEXrvYmLO8VkF5u3lu1xfsq4pQChbyKP3\nn+Khr1wfmlOzQHvosRDyQVr0ZlJ3dgMgw4lomy0WiNSyvAxw+q5/+/IQ3IbdnOIf\n9VVb7o4L162gV8J6TyX72R+O4Hxl7JyiCZlKm03PKjhAXWMwRB/PDM3XFK+JU8z2\npFmHcF4T/RHkgEzfqdzzISqKMwEdsalsLeFiWBCMnw+LrAtc4OJMNu+SeCRtExZh\nqGZTHHULcXOuNKbZkbVERFu9amYKekOGvxqzQ4wLz9ztwzC0TZ23xr++dcGU+21T\nFdQrfX55hlzdja0HKfy1Rnt2Od19M9mbnVdghqB+KQKBgQDtYCcVmH9hnkLTuGuL\nPoZ/enTjtlOGwkkEjIGsq9GxJnfWt/iUC6JKHIOAQ5q/bhjTx0OisgcNtnECMgje\naU+AS03JzRNhB/b6v1lfHnKNfyKyRm8IJDGTQ2lQpqUXOGH+5LjBuDsTyBl1WCDy\nCL8Y07mEqG2Ev/+/s4ayLhIGdQKBgQDpK5GjvkyeansQp78fmd2POIBN1GyGYXJX\nn72oFWw91C5nwCZFKFxMMW5bFU+O5mH17/UaZbzdqQDy1RSJlt8Zt/ARgOD4/akR\nuqIrNribsYCzxNDxydshclMlnr92YXtpYSTos/lJIHuFopNyZwf7jNOYsEBeNBKJ\n02NEIhG/9wKBgQCr+RVX1/uxRW805E9Fui7G/Hji4Jzy7J7p5MGtz21D4pK/xNka\nqLMS7kV3D4N1XNYv2BVwMXpavOpypL04JSOr1uKsaR65FYQhda/R8cUcLhd9APo/\n87jW7+fEvnass/SLLjmMX2StmDKZiReVQjDwU7P8H+n4WwF2aSIUxLvaYQKBgQDT\n7gzW5o2fYyruDXnS0DgoB/PeSdhGH+YcrI1ma+pRHDz9ghGGxFN30Wn7kZgZS174\neZyu3I/YbNb24CNll2K6bovebOSOi4gTHC5v1rHemWxgeOBtE8p/UPkv9WUSxTG1\nq10vwP0wsTx0TztzPSBtTCe63V/z/6Jl8WOFNu4pKwKBgAtUsGD9PGDtqIwfaXws\nV6r7lEIN2JjYzQhJvE9udhuU9Z5dG/ex9Jj+Sq2R57819Zog4KJugbiZiOUit/Kj\nTGc5S6wvRSihOrTv0h0EtgSNH0+dn7k9IWPbfDePWOR8IxZdI2i5JLao+G2EmyWC\nhAAhmYtu55Kqpb97BfAJt+DT\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-uswym@blockchain-b2f62.iam.gserviceaccount.com","client_id":"105747067689313799076","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-uswym%40blockchain-b2f62.iam.gserviceaccount.com","universe_domain":"googleapis.com"}
            - RABBITMQ_URI=amqps://eoivswjo:sT_61rvaXlADxuLMiDO2w3-jx-nVzYq3@porpoise.rmq.cloudamqp.com/eoivswjo
            - JWT_SECRET=27602675b27d5d1b2798d59ab86f0f7cfe616d9bdc6748f7e7645d3e24bca029
            - PASSWORD_PEPPER=78e8814748da1a8
        networks:
            - blockchain

    blockchaindb:
        platform: linux/amd64
        image:  mcr.microsoft.com/mssql/server:2022-latest 
        container_name: blockchaindb
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=123456a@
            - MSSQL_PID=Express
        networks:
            - blockchain
        volumes:
          - C:\dados\volumes\sqlserver:/var/opt/mssql/data
        ports:
            - 1433:1433

    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        networks:
            - blockchain
        ports:
            - 5672:5672
            - 15672:15672